/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE karyawanBaseService PLEASE EDIT ../karyawan.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Karyawan } from '../../domain/mrtproject_db/karyawan';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../karyawan.service.ts
 */

/*
 * SCHEMA DB karyawan
 *
	{
		name: {
			type: 'String',
			required : true
		},
		nik: {
			type: 'Number',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_karyawan: {
			type: Schema.ObjectId,
			ref : "schedule"
		},
	}
 *
 */
@Injectable()
export class KaryawanBaseService {

    contextUrl: string = environment.endpoint + '/karyawan';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * karyawanService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Karyawan): Observable<Karyawan> {
        return this.http
            .post<Karyawan>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * karyawanService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * karyawanService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Karyawan> {
        return this.http
            .get<Karyawan>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * karyawanService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Karyawan[]> {
        return this.http
            .get<Karyawan[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * karyawanService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Karyawan): Observable<Karyawan> {
        return this.http
            .post<Karyawan>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
