/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE scheduleBaseService PLEASE EDIT ../schedule.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Schedule } from '../../domain/mrtproject_db/schedule';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../schedule.service.ts
 */

/*
 * SCHEMA DB schedule
 *
	{
		date: {
			type: 'Date',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_karyawan: {
			type: Schema.ObjectId,
			ref : "schedule"
		},
		_shift: {
			type: Schema.ObjectId,
			ref : "schedule"
		},
	}
 *
 */
@Injectable()
export class ScheduleBaseService {

    contextUrl: string = environment.endpoint + '/schedule';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * scheduleService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Schedule): Observable<Schedule> {
        return this.http
            .post<Schedule>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * scheduleService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * scheduleService.findBy_karyawan
    *   @description CRUD ACTION findBy_karyawan
    *   @param Objectid key Id della risorsa _karyawan da cercare
    *
    */
    findBy_karyawan(id: string): Observable<Schedule[]> {
        return this.http
            .get<Schedule[]>(this.contextUrl + '/findBy_karyawan/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * scheduleService.findBy_shift
    *   @description CRUD ACTION findBy_shift
    *   @param Objectid key Id della risorsa _shift da cercare
    *
    */
    findBy_shift(id: string): Observable<Schedule[]> {
        return this.http
            .get<Schedule[]>(this.contextUrl + '/findBy_shift/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * scheduleService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Schedule> {
        return this.http
            .get<Schedule>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * scheduleService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Schedule[]> {
        return this.http
            .get<Schedule[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * scheduleService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Schedule): Observable<Schedule> {
        return this.http
            .post<Schedule>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
